[package]
name = "ativ-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
description = "ATIV's shared media interface to AVID Core."
rust-version.workspace = true

[lib]
name = "ativ_core"
path = "src/lib.rs"

[dependencies]
avid-core.workspace = true

[build-dependencies]
toml = "0.8"
