[workspace]
members = [
    "crates/ativ-core",
    "crates/ativ-engine",
    "crates/ativ-update",
]
resolver = "2"

[workspace.package]
version = "0.2.3"
edition = "2024"
license = "GPL-3.0-or-later"
repository = "https://github.com/tlolabs/ativ"
rust-version = "1.85"

[workspace.dependencies]
avid-core = { git = "https://github.com/tlolabs/avid-core", rev = "eab97dd043187aa8b7a1cae4eb2c1228fa25a9db" }

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
