[workspace]
members = [
    "crates/ativ-core",
    "crates/ativ-engine",
    "crates/ativ-update",
]
resolver = "2"

[workspace.package]
version = "0.2.2"
edition = "2024"
license = "GPL-3.0-or-later"
repository = "https://github.com/tlolabs/ativ"
rust-version = "1.85"

[workspace.dependencies]
avid-core = { path = "../AVID Core" }

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
