[package]
name = "ativ-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
description = "ATIV's local media engine."
rust-version.workspace = true

[[bin]]
name = "ativ-engine"
path = "src/main.rs"

[dependencies]
ativ-core = { path = "../ativ-core" }
serde_json = "1"
sha2 = "0.10"
